---
unk_idx: 0
pad_idx: 1
bos_idx: 2
eos_idx: 3

path_data: 'C:\Users\Zak\auto_placement_accents\data' # путь в папку с данными
path_model: 'C:\Users\Zak\auto_placement_accents\models\accent_model_3.pth' # путь к весам модели

src_data: 'not_accent'
tgt_data: 'accent'

#  Настраиваемые параметры модели
num_layers: 6 # Это количество слоев в трансформере
max_seq_length: 100 #  Максимальная длина последовательности
dropout: 0.1 #  Вероятность отключения каждого элемента входных данных во время обучения для предотвращения переобучения.
batch_size: 4 # Количество предложений в пакете
emb_size: 512 # Размерность эмбеддинга для каждого токена
n_head: 8 #Это количество "голов" в механизме внимания
ffn_hid_dim: 512 # Размер скрытого слоя
num_encoder_layers: 3 # Количество слоев в энкодере трансформера.
num_decoder_layers: 3 # Количество слоев в декодере трансформера.